export const profileDataStructure = {
  user: '',
  company_name: '',
  currency: 'USD',
  model_start_date: '2022-01-01',
  initial_cash_balance: '120000',
  taxes: {
    income_tax_rate: '21',
    inflation: '3',
  },
  valuation: {
    business_terminal_value: 'xEBITDA',
    discount_rate_today: '25',
    xEBITDA: '10',
    debt_capital_ratio: '0',
    debt_interest_rate: '12',
  },
  operating_cash: {
    balance: '120000',
    percentage_of_revenues: '10',
    pending_income_total_income: '0',
    prepaid_days_outstanding: '30',
    accounts_payable: '20',
  },
  capital_expenditures: {
    estimate_new_computers: 'Yes',
    price_per_computer: '2000',
  },
  assets_depreciation_time: {
    apartment_office_fixings: '10',
    office_furniture: '5',
    computers: '3',
    telecom_equipment: '5',
    tech_infrastructure: '5',
    other: '5',
  },
  team: [
    {
      role: 'CEO',
      category: 'Ops',
      subCategory: '',
      salary: '30000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '1',
      period_of_new_hires: 'Never',
      maximum_number: '1',
      annual_increase: '5',
    },
    {
      role: 'COO',
      category: 'Ops',
      subCategory: '',
      salary: '30000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '1',
      period_of_new_hires: 'Never',
      maximum_number: '1',
      annual_increase: '5',
    },
    {
      role: 'Office Manager',
      category: 'Ops',
      subCategory: '',
      salary: '0',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Annually',
      maximum_number: '0',
      annual_increase: '5',
    },
    {
      role: 'CTO',
      category: 'R&D',
      subCategory: '',
      salary: '30000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '1',
      period_of_new_hires: 'Never',
      maximum_number: '1',
      annual_increase: '5',
    },
    {
      role: 'VP of Product',
      category: 'R&D',
      subCategory: '',
      salary: '0',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Annually',
      maximum_number: '0',
      annual_increase: '5',
    },
    {
      role: 'UI/UX',
      category: 'R&D',
      subCategory: '',
      salary: '4000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '1',
      period_of_new_hires: 'Annually',
      maximum_number: '1',
      annual_increase: '5',
    },
    {
      role: 'Senior developers',
      category: 'R&D',
      subCategory: '',
      salary: '10000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '1',
      period_of_new_hires: 'Quarterly',
      maximum_number: '1',
      annual_increase: '5',
    },
    {
      role: 'Junior developers',
      category: 'R&D',
      subCategory: '',
      salary: '50000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '1',
      period_of_new_hires: 'Quarterly',
      maximum_number: '1',
      annual_increase: '5',
    },
    {
      role: 'VP of Sales',
      category: 'Growth',
      subCategory: 'Sales',
      salary: '60000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Never',
      maximum_number: '0',
      annual_increase: '5',
    },
    {
      role: 'Inbound Sales Agent',
      category: 'Growth',
      subCategory: 'Sales',
      salary: '50000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Quarterly',
      maximum_number: '0',
      annual_increase: '5',
    },
    {
      role: 'Outbound Sales Agent',
      category: 'Growth',
      subCategory: 'Sales',
      salary: '50000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Monthly',
      maximum_number: '10',
      annual_increase: '5',
    },
    {
      role: 'VP of Marketing/CMO',
      category: 'Growth',
      subCategory: 'Marketing',
      salary: '60000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Never',
      maximum_number: '0',
      annual_increase: '5',
    },
    {
      role: 'Senior Marketing',
      category: 'Growth',
      subCategory: 'Marketing',
      salary: '50000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Quarterly',
      maximum_number: '0',
      annual_increase: '5',
    },
    {
      role: 'Junior Marketing',
      category: 'Growth',
      subCategory: 'Marketing',
      salary: '40000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Monthly',
      maximum_number: '0',
      annual_increase: '5',
    },
    {
      role: 'Head of Customer',
      category: 'Ops',
      subCategory: '',
      salary: '60000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Never',
      maximum_number: '0',
      annual_increase: '5',
    },
    {
      role: 'Senior Customer Support',
      category: 'Ops',
      subCategory: '',
      salary: '50000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Quarterly',
      maximum_number: '0',
      annual_increase: '5',
    },
    {
      role: 'Junior Customer Support',
      category: 'Ops',
      subCategory: '',
      salary: '40000',
      taxes_and_benefits: '10',
      date_hired: '2022-07-01',
      number_of_new_hires: '0',
      period_of_new_hires: 'Quarterly',
      maximum_number: '0',
      annual_increase: '5',
    },
  ],
  fundraising_close_date: '2022-07-01',
  investment_amount: '250000',
  brand_awareness_budget: {
    starting_budget: '3000',
    monthly_marketing_budget_increase: '3500',
    maximum_marketing_budget: '5000',
  },
  website_traffic: {
    start_date: '2022-07-01',
    traffic_at_launch: '100',
    monthly_increase: '30',
    maximum_traffic: '1000000',
  },
  self_service_subscriptions: true,
  self_service_business_model: {
    launch_date: '2022-07-01',
    ARPU: '60',
    billing_term: 'Monthly',
    churn_rate: '20',
    lifetime_value: '300',
  },
  self_service_conversion_to_paid: '20',
  self_service_paid_traffic: {
    starting_marketing_budget: '3000',
    marketing_budget_increase: '3500',
    maximum_paid_ads_budget: '300000',
    expected_CAC: '10',
    monthly_CAC_change: '3',
    minimum_CAC_possible: '80',
  },
  inbound_sales: false,
  inbound_sales_business_model: {
    launch_date: '2022-05-01',
    ARPU: '299',
    billing_term: 'Monthly',
    churn_rate: '10',
    lifetime_value: '2990',
  },
  inbound_sales_conversion_to_paid: '1',
  inbound_sales_paid_traffic: {
    starting_marketing_budget: '15000',
    marketing_budget_increase: '50',
    maximum_paid_ads_budget: '1500000',
    expected_CAC: '50',
    monthly_CAC_change: '5',
    minimum_CAC_possible: '15',
  },
  inbound_sales_agent_lead_nurturing: {
    leads_per_agent: '100',
    role: 'Inbound Sales Agent',
  },
  inbound_sales_lead_sale_conversion: '10',
  outbound_sales: false,
  outbound_sales_business_model: {
    launch_date: '2022-06-01',
    ARPU: '500',
    billing_term: 'Monthly',
    churn_rate: '2',
    lifetime_value: '25000',
  },
  outbound_sales_reachout: {
    role: 'Outbound Sales Agent',
    number_of_new_agents: '2',
    maximum_number_of_agents: '10',
    deals_closed_per_month: '1',
    sales_cycle_time: '6',
  },
  sga: {
    office_per_desk_cost: '400',
    tech_support_customers_per_agent: '100',
    tech_support_role: 'Junior Customer Support',
  },
  cogs: [
    { name: 'AWS', category: 'Web Services', cost: '0' },
    { name: 'Intercom', category: 'Web Services', cost: '0' },
    { name: 'Service 1', category: 'Other', cost: '0' },
    { name: 'Service 2', category: 'Other', cost: '0' },
    { name: 'Service 1', category: 'Payment Processing', cost: '0' },
    { name: 'Service 2', category: 'Payment Processing', cost: '0' },
  ],
  operating_expenses: [
    { name: 'Mailchimp', category: 'Marketing & Growth', subCategory: 'Platforms', cost: '0' },
    { name: 'Hubspot', category: 'Marketing & Growth', subCategory: 'Platforms', cost: '0' },
    {
      name: 'Google Ads',
      category: 'Marketing & Growth',
      subCategory: 'Direct Response Campaigns',
      cost: '0',
    },
    {
      name: 'Facebook/Instagram',
      category: 'Marketing & Growth',
      subCategory: 'Brand Awareness Campaigns',
      cost: '0',
    },
    { name: 'Legal', category: 'Advisory & Prof. Services', subCategory: 'Recurring', cost: '0' },
    {
      name: 'Professional',
      category: 'Advisory & Prof. Services',
      subCategory: 'Recurring',
      cost: '0',
    },
    {
      name: 'Accounting',
      category: 'Advisory & Prof. Services',
      subCategory: 'Recurring',
      cost: '0',
    },
    { name: 'Other', category: 'Advisory & Prof. Services', subCategory: 'Recurring', cost: '0' },
    { name: 'Legal', category: 'Advisory & Prof. Services', subCategory: 'One-Time', cost: '0' },
    {
      name: 'Professional',
      category: 'Advisory & Prof. Services',
      subCategory: 'One-Time',
      cost: '0',
    },
    {
      name: 'Accounting',
      category: 'Advisory & Prof. Services',
      subCategory: 'One-Time',
      cost: '0',
    },
    { name: 'Other', category: 'Advisory & Prof. Services', subCategory: 'One-Time', cost: '0' },
    { name: 'Apartment', category: 'Rent', subCategory: '', cost: '0' },
    { name: 'Other', category: 'Rent', subCategory: '', cost: '0' },
    {
      name: 'Slidebean (Presentations)',
      category: 'Tech Support & Services',
      subCategory: '',
      cost: '0',
    },
    {
      name: 'Gmail',
      category: 'Tech Support & Services',
      subCategory: '',
      cost: '0',
    },
    { name: 'Employees', category: 'Insurance', subCategory: '', cost: '0' },
    { name: 'Assets', category: 'Insurance', subCategory: '', cost: '0' },
    { name: 'Other', category: 'Insurance', subCategory: '', cost: '0' },
    { name: 'Power', category: 'Utilities', subCategory: '', cost: '0' },
    { name: 'Internet', category: 'Utilities', subCategory: '', cost: '0' },
    { name: 'Phone', category: 'Utilities', subCategory: '', cost: '0' },
    { name: 'Water', category: 'Utilities', subCategory: '', cost: '0' },
    { name: 'Other', category: 'Utilities', subCategory: '', cost: '0' },
    { name: 'Bank Fees', category: 'Other Expenses', subCategory: '', cost: '0' },
    { name: 'Travel', category: 'Other Expenses', subCategory: '', cost: '0' },
  ],
}

//   const [data, setData] = useState({
//     companyName: '',
//     currency: '',
//     modelStartDate: '',
//     startCapital: '',
//     cashBalance: '',
//     incomeTaxRate: '',
//     inflation: '',
//     discountRate: '',
//     xEBITDA: '',
//     debtCapitalRatio: '',
//     debtInterestRate: '',
//     balance: '',
//     percentageOfRevenues: '',
//     pendingIncomeTotalIncome: '',
//     prepaidDaysOutstanding: '',
//     pricePerComputer: '',
//     apartmentOfficeFixings: '',
//     pricePerComputer2: '',
//     officeFurniture: '',
//     telecomEquipment: '',
//     operations: [{ roleName: '', salary: '' }],
//     lastStep: [],
//   })
